name: embedding
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - openai>=1.0.0
      - PyPDF2>=3.0.0
      - tiktoken>=0.6.0
      - sentence-transformers
      - flask
